# Generated by Django 5.0.3 on 2024-03-14 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noderedapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noderedmodel',
            name='ValorContagem',
        ),
        migrations.AddField(
            model_name='noderedmodel',
            name='Valor_Contagem',
            field=models.IntegerField(db_column='Valor Contagem', default=0),
        ),
        migrations.AlterField(
            model_name='noderedmodel',
            name='Botao',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='noderedmodel',
            name='LigaRobo',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='noderedmodel',
            name='ResetContador',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='noderedmodel',
            name='Sensor',
            field=models.BooleanField(),
        ),
    ]
